<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxdjW05\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxdjW05/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXxdjW05.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXxdjW05\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXxdjW05\App_KernelDevDebugContainer([
    'container.build_hash' => 'XxdjW05',
    'container.build_id' => '46a809d6',
    'container.build_time' => 1769539327,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxdjW05');
