<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWz3vdhL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWz3vdhL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWz3vdhL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWz3vdhL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWz3vdhL\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wz3vdhL',
    'container.build_id' => '5d30a38d',
    'container.build_time' => 1766830593,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWz3vdhL');
