<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDAlWtuV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDAlWtuV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDAlWtuV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDAlWtuV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDAlWtuV\App_KernelDevDebugContainer([
    'container.build_hash' => 'DAlWtuV',
    'container.build_id' => 'cd2c9580',
    'container.build_time' => 1770891981,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDAlWtuV');
